name = "Altv Sirius"
host = "0.0.0.0"
env = "dev"
port = 7788
players = 150
announce = false
gamemode = "Roleplay"
website = "athenaframework.com"
language = "de"
description = "With Reconnect On - Vue Debug - 1 Player Only"
debug = true
streamingDistance = 400
migrationDistance = 150
modules = ["js-module"]
resources = ["core"]
tags = ["athena","framework","version",""]
vue-athena = true
log-streams = ["console", "file", "console", "stdconsole"]
